<a href="https://colab.research.google.com/github/guupiii/ESAA/blob/main/YB_0905_Numpy_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#### 21. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

[[0.11210372 0.47938831 0.36631658]
 [0.95296722 0.66019569 0.63969674]
 [0.77976669 0.41348059 0.16771988]
 [0.61374522 0.70972269 0.77950015]
 [0.04234597 0.20519043 0.00628375]]
[[0.22027825 0.34960401]
 [0.50725646 0.01106194]
 [0.01345533 0.15929231]]
<built-in function dot>


#### 22. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

[ 0  1  2  3 -4 -5 -6 -7  8  9]


#### 23. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

#### 24. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

#### 25. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

<ipython-input-64-cd809174da5d>:1: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)
<ipython-input-64-cd809174da5d>:2: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)
<ipython-input-64-cd809174da5d>:3: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float)


array([-9.22337204e+18])

#### 26. How to find common values between two arrays? (★☆☆)
```python
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
```
Hint : use `numpy.random.randint(start, end, size)`

[4 1 3 2 4 6 0 9 7 9]
[4 1 1 7 3 8 7 9 9 3]
[1 3 4 7 9]


Z1: [4 5 8 8 9 8 5 9 9 7]
Z2: [6 3 7 7 0 6 0 9 2 7]
[7 9]


#### 27. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

False. nan!=1j


<ipython-input-67-16339fbc685e>:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

#### 28. How to get all the dates corresponding to the month of July 2016? (★★☆)
Hint : modify the code below
```python
Z = np.arange('start', 'end', dtype='datetime64[D]')
```

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 29. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)
Hint : use `numpy.add`, `numpy.divide`,`numpy.negative`, `numpy.multiply` and parameter `out` of the funtions

In [34]:
import numpy as np
A = np.ones((3,3))
B = np.full((3,3), 2.0)
print(A)
print(B)
np.add(A, B, out=A)
np.divide(A, 2, out=B)
np.negative(B,out=B)
np.multiply(A, B, out=A)
print(A)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]
[[-4.5 -4.5 -4.5]
 [-4.5 -4.5 -4.5]
 [-4.5 -4.5 -4.5]]


#### 30. Extract the integer part of a random array of positive numbers using 2 different methods (★★☆)
Hint : `%`, `//`

[6. 7. 9. 2. 4.]


#### 31. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [2]:
import numpy as np
a = np.zeros((5,5))
a += np.arange(5)
print(a)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 32. Create a random vector of size 10 and sort it (★★☆)

In [4]:
a = np.random.random(10)
a.sort()
a

array([0.25101109, 0.36764255, 0.50744128, 0.56968376, 0.60360134,
       0.77059141, 0.86969814, 0.90099469, 0.92296215, 0.93815682])

#### 33. Consider two random array A and B, check if they are equal (★★☆)
```python
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
```
Hint : Use `numpy.array_equal()`

In [6]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
np.array_equal(A, B)

False

#### 34. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)
Hint 1 : Note that cartesian coodinate **(x, y)** can be represented as  polar coordinates **(distance from origin to (x,y), angle from the x-axis)**

Hint 2 : Use `numpy.sqrt` and `numpy.arctan2`

In [22]:

a = np.random.random((10, 2))

x, y = a[:, 0], a[:, 1]
r = np.sqrt(x**2 + x**2)
t = np.arctan2(y, x)

print(x)
print(y)
print(r)
print(t)

[0.97380014 0.57552931 0.64820094 0.93070118 0.19035073 0.07082299
 0.38463038 0.81025907 0.11647792 0.10627285]
[0.4233526  0.52622987 0.00848849 0.9645027  0.73684259 0.7639918
 0.06789961 0.26693134 0.8532528  0.13509129]
[1.37716137 0.81392136 0.91669456 1.31621024 0.26919659 0.10015883
 0.5439495  1.14587937 0.16472466 0.1502925 ]
[0.41009386 0.74068188 0.01309472 0.80323157 1.31799038 1.47835927
 0.17473185 0.31824201 1.43512448 0.90423377]


#### 35. Create random vector Z of size 10 and replace the maximum value by 0 (★★☆)
Hint : We can see the index of maximum value using `Z.argmax()`

In [13]:
import numpy as np

a = np.random.random(10)
print(a)
a[a.argmax()] = 0
a

[0.27395918 0.41875343 0.35420194 0.83567688 0.09536464 0.69048992
 0.76393147 0.95615033 0.24274215 0.60575458]


array([0.27395918, 0.41875343, 0.35420194, 0.83567688, 0.09536464,
       0.69048992, 0.76393147, 0.        , 0.24274215, 0.60575458])

#### 36. How to find the closest value (to a given scalar v) in a vector Z? (★★☆)
```python
Z = np.arange(100)
v = np.random.uniform(0,100)
```
Hint : Coumpute the distances between the each elements of Z and the scalar v. After that, we can see the index of minimum value using `argmin()`.  

In [24]:
Z = np.arange(100)
v = np.random.uniform(0, 100)

b = np.abs(Z - v)

index = b.argmin()

c = Z[index]
print(c)

v = 20.49081519852799
20


#### 37. What is the equivalent of enumerate for numpy arrays? (★★☆)
Hint : Use `numpy.ndenumerate()`or `numpy.ndindex()`

Example of the output :
```python
Z = np.arange(9).reshape(3,3)
```
```python
# output
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
```

In [28]:
import numpy as np

Z = np.arange(9).reshape(3, 3)

for idx, val in np.ndenumerate(Z):
    print(idx, val)


(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 38. How to randomly place p elements in a 2D array? (★★☆)
Hint : modify the code below
```python
n = 'size of a 2D array'
p = 'the number of elements that you want to place'
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace = False),'value that you want to place')
print(Z)
```

In [15]:
n = 5
p = 8
Z = np.zeros((n, n))

np.put(Z, np.random.choice(range(n*n), p, replace=False), 1)

print(Z)

[[1. 0. 0. 1. 0.]
 [0. 0. 1. 1. 0.]
 [1. 0. 0. 0. 0.]
 [1. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0.]]


#### 39. How to sort an array below by the nth column? (★★☆)
```python
Z = np.random.randint(0,10,(3,3))
```

In [20]:
import numpy as np
n =2
Z = np.random.randint(0, 10, (3, 3))
Z_sorted = Z[Z[:, n].argsort()]
print("\nAfter sorting by column", n, ":\n", Z_sorted)


After sorting by column 2 :
 [[7 0 4]
 [6 9 8]
 [3 8 9]]


[[7 6 7]
 [7 8 4]
 [5 4 7]]


array([[5, 4, 7],
       [7, 6, 7],
       [7, 8, 4]])

[[7 9 5]
 [1 8 2]
 [6 8 1]]


array([[6, 8, 1],
       [1, 8, 2],
       [7, 9, 5]])