<a href="https://colab.research.google.com/github/guupiii/ESAA/blob/main/YB_0905_Numpy_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#### 21. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [7]:
import numpy as np

# Alternative solution, in Python 3.5 and above
Z = np.ones((5,3)) @ np.ones((3,2))
print(Z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


#### 22. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [8]:
# Author: Evgeni Burovski

Z = np.arange(11)
Z[(3 < Z) & (Z < 8)] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


#### 23. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [9]:
# Author: Jake VanderPlas

print(sum(range(5),-1))    # 결과 : 9
from numpy import *
print(sum(range(5),-1))     # 결과 : 10

9
10


#### 24. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [10]:
Z=np.arange(9).reshape(3,3)
#legal
print(Z**Z)
print(2 << Z >> 2)
print(Z <- Z)
print(1j*Z)
print(Z/1/1)


# Z<Z>Z -> X illegal   < 마지막 것이 올바르지 않은 표현이다!

[[       1        1        4]
 [      27      256     3125]
 [   46656   823543 16777216]]
[[  0   1   2]
 [  4   8  16]
 [ 32  64 128]]
[[False False False]
 [False False False]
 [False False False]]
[[0.+0.j 0.+1.j 0.+2.j]
 [0.+3.j 0.+4.j 0.+5.j]
 [0.+6.j 0.+7.j 0.+8.j]]
[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]


#### 25. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [11]:
print(np.array(0) / np.array(0))   # 결과 : nan
print(np.array(0) // np.array(0))   # 결과 : 0에 가까운 수
print(np.array([np.nan]).astype(int).astype(float))   # 결과 : 오

nan
0
[-9.22337204e+18]


/tmp/ipython-input-2591757108.py:1: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))   # 결과 : nan
/tmp/ipython-input-2591757108.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))   # 결과 : 0에 가까운 수
/tmp/ipython-input-2591757108.py:3: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float))   # 결과 : 오


#### 26. How to find common values between two arrays? (★☆☆)
```python
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
```
Hint : use `numpy.random.randint(start, end, size)`

In [12]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(np.intersect1d(Z1,Z2))

[0 2 5 8]


#### 27. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

False. nan!=1j


In [13]:
np.sqrt(-1) == np.emath.sqrt(-1)   # 결과 : False

/tmp/ipython-input-2520232100.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)   # 결과 : False


np.False_

#### 28. How to get all the dates corresponding to the month of July 2016? (★★☆)
Hint : modify the code below
```python
Z = np.arange('start', 'end', dtype='datetime64[D]')
```

In [14]:
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 29. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)
Hint : use `numpy.add`, `numpy.divide`,`numpy.negative`, `numpy.multiply` and parameter `out` of the funtions

In [15]:
import numpy as np
A = np.ones((3,3))
B = np.full((3,3), 2.0)
print(A)
print(B)
np.add(A, B, out=A)
np.divide(A, 2, out=B)
np.negative(B,out=B)
np.multiply(A, B, out=A)
print(A)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]
[[-4.5 -4.5 -4.5]
 [-4.5 -4.5 -4.5]
 [-4.5 -4.5 -4.5]]


#### 30. Extract the integer part of a random array of positive numbers using 2 different methods (★★☆)
Hint : `%`, `//`

In [16]:
Z = np.random.uniform(0,10,10)

print(Z - Z%1)
print(Z // 1)

# 다른 방법들(2가지 초과이므로 참고만 할 것!)
print(np.floor(Z))
print(Z.astype(int))
print(np.trunc(Z))

[0. 8. 7. 7. 3. 2. 9. 9. 0. 0.]
[0. 8. 7. 7. 3. 2. 9. 9. 0. 0.]
[0. 8. 7. 7. 3. 2. 9. 9. 0. 0.]
[0 8 7 7 3 2 9 9 0 0]
[0. 8. 7. 7. 3. 2. 9. 9. 0. 0.]


#### 31. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [17]:
import numpy as np
a = np.zeros((5,5))
a += np.arange(5)
print(a)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 32. Create a random vector of size 10 and sort it (★★☆)

In [18]:
a = np.random.random(10)
a.sort()
a

array([0.4028319 , 0.41962579, 0.44687795, 0.512729  , 0.51870534,
       0.58854196, 0.78846305, 0.82161659, 0.9475009 , 0.98501666])

#### 33. Consider two random array A and B, check if they are equal (★★☆)
```python
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
```
Hint : Use `numpy.array_equal()`

In [19]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
np.array_equal(A, B)

False

#### 34. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)
Hint 1 : Note that cartesian coodinate **(x, y)** can be represented as  polar coordinates **(distance from origin to (x,y), angle from the x-axis)**

Hint 2 : Use `numpy.sqrt` and `numpy.arctan2`

In [20]:

a = np.random.random((10, 2))

x, y = a[:, 0], a[:, 1]
r = np.sqrt(x**2 + x**2)
t = np.arctan2(y, x)

print(x)
print(y)
print(r)
print(t)

[0.90186292 0.53620027 0.72384716 0.42133596 0.62269602 0.40784216
 0.92379591 0.65675658 0.62967334 0.53333781]
[0.34040318 0.88368426 0.42290445 0.44496615 0.88143672 0.88925954
 0.12192399 0.36441094 0.36742557 0.76134531]
[1.27542677 0.75830169 1.02367447 0.59585903 0.88062515 0.57677591
 1.30644471 0.92879406 0.89049258 0.75425356]
[0.36091205 1.02540782 0.52875477 0.81266847 0.95575079 1.14078793
 0.1312231  0.50657031 0.52821204 0.95972129]


#### 35. Create random vector Z of size 10 and replace the maximum value by 0 (★★☆)
Hint : We can see the index of maximum value using `Z.argmax()`

In [21]:
import numpy as np

a = np.random.random(10)
print(a)
a[a.argmax()] = 0
a

[0.91932847 0.54601899 0.94353333 0.33475613 0.62619417 0.84226604
 0.02978354 0.2990238  0.519663   0.75762794]


array([0.91932847, 0.54601899, 0.        , 0.33475613, 0.62619417,
       0.84226604, 0.02978354, 0.2990238 , 0.519663  , 0.75762794])

#### 36. How to find the closest value (to a given scalar v) in a vector Z? (★★☆)
```python
Z = np.arange(100)
v = np.random.uniform(0,100)
```
Hint : Coumpute the distances between the each elements of Z and the scalar v. After that, we can see the index of minimum value using `argmin()`.  

In [22]:
Z = np.arange(100)
v = np.random.uniform(0, 100)

b = np.abs(Z - v)

index = b.argmin()

c = Z[index]
print(c)

22


#### 37. What is the equivalent of enumerate for numpy arrays? (★★☆)
Hint : Use `numpy.ndenumerate()`or `numpy.ndindex()`

Example of the output :
```python
Z = np.arange(9).reshape(3,3)
```
```python
# output
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
```

In [23]:
import numpy as np

Z = np.arange(9).reshape(3, 3)

for idx, val in np.ndenumerate(Z):
    print(idx, val)


(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 38. How to randomly place p elements in a 2D array? (★★☆)
Hint : modify the code below
```python
n = 'size of a 2D array'
p = 'the number of elements that you want to place'
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace = False),'value that you want to place')
print(Z)
```

In [24]:
n = 5
p = 8
Z = np.zeros((n, n))

np.put(Z, np.random.choice(range(n*n), p, replace=False), 1)

print(Z)

[[0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [1. 0. 0. 1. 1.]
 [0. 0. 1. 0. 0.]
 [1. 0. 0. 1. 1.]]


#### 39. How to sort an array below by the nth column? (★★☆)
```python
Z = np.random.randint(0,10,(3,3))
```

In [25]:
# column 1
Z = np.random.randint(0,10,(3,3))

print(Z)
print(Z[Z[:,0].argsort()])

[[0 8 9]
 [3 1 6]
 [6 5 4]]
[[0 8 9]
 [3 1 6]
 [6 5 4]]


In [26]:
# column 2
print(Z)
print(Z[Z[:,1].argsort()])

[[0 8 9]
 [3 1 6]
 [6 5 4]]
[[3 1 6]
 [6 5 4]
 [0 8 9]]


In [27]:
# column 3
print(Z)
print(Z[Z[:,2].argsort()])

[[0 8 9]
 [3 1 6]
 [6 5 4]]
[[6 5 4]
 [3 1 6]
 [0 8 9]]
